routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/',[UserController::class, 'index']);

Route::resources([
    'users' => UserController::class,
]);

Route::get('/user/{user}', [UserController::class, 'converter']);






// Route::get('/',[UserController::class, 'index']);
// Route::get('/create',[UserController::class, 'create']);
// Route::get('/user/{id}', [UserController::class, 'show']);
// Route::post('/addUser', [UserController::class, 'store']);
// Route::patch('/updateUser/{id}', [UserController::class, 'update']);
// Route::post('/DeleteUser/{id}', [UserController::class, 'destroy']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'currency',
        'amount',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

use App\Converter\Facade\Currency;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $user = User::latest()->paginate('10');

        return view('welcome', compact('user'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {    
        $inputVal= $request->all();
        //
        $validatedData = $request->validate([
            'name' => 'required|unique:users|max:255',
            'email' => 'required|email',
            'amount' => 'required|numeric',
            'currency' => 'required|in:GBP,EUR,USD',
        ]);
        $user = User::create($request->all() + ['password' => 'password']);


    
        return redirect('/')->with('status', 'User Added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
           $user = User::findOrFail($id);

           return view('profile', compact('user'));




    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::findOrFail($id);

        return view('edit', compact('user'));
    

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email',
            'amount' => 'required|numeric',
            'currency' => 'required|in:GBP,EUR,USD',
        ]);
        $user = User::findOrFail($id);
        $user->update($request->except('_method', '_token'));
        return redirect('/')->with('status', 'Update Successful!');




    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::findOrFail($id);
        $user->delete();
        return redirect('/')->with('status', 'Record Deleted!');



    }
       
    public function converter(Request $request, User $user)
        {
          $options = $request->rate_option;
          if($options == 'local' || $options == ''){

          $converted = Currency::from($user->currency)->to($request->currency)->amount($user->amount)->convert();
            
          }else{
         $converted = Currency::createExternalRatesApiDriver()->from($user->currency)->to($request->currency)->amount($user->amount)->convert();
          
        }        
          $user->currency = $request->currency;
          $user->amount = round($converted, 2);
    
         
    
          return response()->json($user);
        }











}

resources/views/_partials/_footer.blade.php
         </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../js/bootstrap.min.js"></script>

</body>

</html>

resources/views/_partials/_header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{ config('app.name') }} - @yield('title')</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../css/sb-admin.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../../font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

resources/views/_partials/_top.blade.php
<!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Executives Place - Technical test Solution
</a>
            </div>
            <!-- Top Menu Items -->
           <ul class="nav navbar-right top-nav">
               {{--   <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>--}}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Welcome Oghenerukevwe <b class="caret"></b></a>
                    {{-- <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul> --}}
                </li>
            </ul> 
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="{{ route('users.create') }}"><i class="fa fa-fw fa-users"></i> Add User</a>
                    </li>
                    {{-- <li>
                        <a href="tables.html"><i class="fa fa-fw fa-table"></i> Tables</a>
                    </li>
                    <li>
                        <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Forms</a>
                    </li>
                    <li>
                        <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
                    </li>
                    <li>
                        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
                    </li>
                    <li>
                        <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
                    </li> --}}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

resources/views/add.blade.php
@extends('layouts.app')
@section('content')


            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Welcome 
                            <small>Add Users</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="/">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-file"></i> Add Users
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->


     <div class="row">
      @if($errors->any())
        <div class="alert alert-danger">
          @foreach ($errors->all() as $error)
            {{ $error }} <br/>
          @endforeach
        </div>
      @endif
        <div class="col-lg-12">
          <form method="post" action="{{ route('users.store') }}">
            {!! csrf_field() !!}
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <input type="text" class="form-control" id="name" name="name"  placeholder="Name">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <input type="text" class="form-control" id="email" name="email"  placeholder="Email">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <input type="text" class="form-control" id="amount" name="amount"  placeholder="Amount">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <select class="form-control" id="currency" name="currency">
                    <option value="GBP">GBP</option>
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                  </select>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
          </form>
        </div>
      </div>
    </div>
  </div>

            </div>
            <!-- /.container-fluid -->

@endsection
        





 

resources/views/edit.blade.php
@extends('layouts.app')
@section('content')


            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                           {{$user->name}} 
                            <small>Update Record</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="/">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-file"></i>Update User
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->


                <div class="row">
      @if($errors->any())
        <div class="alert alert-danger">
          @foreach ($errors->all() as $error)
            {{ $error }} <br/>
          @endforeach
        </div>
      @endif
        <div class="col-lg-12">
          <form method="POST" action="{{ route('users.update', $user->id) }}">
            {!! csrf_field() !!}
            {{ method_field('PATCH') }}
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <input type="text" class="form-control" id="name" name="name" value="{{ $user->name}}" placeholder="Name">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <input type="text" class="form-control" id="email" name="email" value="{{ $user->email}}"  placeholder="Email">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <input type="text" class="form-control" id="amount" name="amount" value="{{ $user->amount}}" placeholder="Amount">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <div class="input-group">
                  <select class="form-control" id="currency" name="currency">
                    <option  value="{{ $user->currency}}">{{ $user->currency}}</option>
                    <option value="GBP">GBP</option>
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                  </select>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>

            </div>
            <!-- /.container-fluid -->

@endsection
        





 

resources/views/layouts/app.blade.php
@include('_partials._header')


@include('_partials._top')



        <div id="page-wrapper">





           @yield('content')





        </div>
        <!-- /#page-wrapper -->


@include('_partials._footer')

resources/views/profile.blade.php
@extends('layouts.app')
@section('content')


            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            {{$user->name}}
                            <small>Details</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="/">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-file"></i> info
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->


                <table class="table table-bordered">
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th >Email</th>
                  <th >Currency</th>
                  <th >Amount</th>
                  <th style="width: 150px">Convert Currency</th>
                  <th>Convertion Type</th>
                </tr>

                 <tr>
                 <td></td>
                 <td col="5">
                  {{$user->name}} </td>
                <td>{{$user->email}}</td>
                <td>{{$user->currency}}</td>
                <td>{{$user->amount}}</td>
                <td>  
                <form method="GET" action="/user/{{ $user->id }}">
                    <div class="col-lg-12 py-1">
                        {{ csrf_field() }}
                        <select class="form-control" id="currency" name="currency">
                        <option value="GBP" {{$user->currency == 'GBP'  ? 'selected' : ''}}>GBP</option>
                        <option value="USD" {{$user->currency == 'USD'  ? 'selected' : ''}}>USD</option>
                        <option value="EUR" {{$user->currency == 'EUR'  ? 'selected' : ''}}>EUR</option>
                        </select>
                    </div>
               </td>
                <td><div class="form-check form-check-inline">
                    <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="rate_option" id="inlineRadio1" value="local">
                    <label class="form-check-label" for="inlineRadio1">Use Local Convertion Rate (Driver) </label>
                    </div>
                    <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="rate_option" id="inlineRadio2" value="external">
                    <label class="form-check-label" for="inlineRadio2">Use External Convertion Rate (Driver)</label>
                    </div></td><td>
                
                <div class="col-lg-12 py-1">
            <button type="submit" class="btn btn-primary">Convert</button>
          </div>
        </form></td>
                
                </tr>

                </table>

            </div>
            <!-- /.container-fluid -->

@endsection
        





 